[platformio]
default_envs = mik32v2

[env:mik32v2]
platform = https://github.com/MikronMIK32/platform-mik32.git#v0.3.0
platform_packages =
  framework-mik32v2-sdk @ https://gitflic.ru/project/mikron-mik32/framework-mik32v2-sdk.git#v0.2.2
  tool-mik32-uploader @ https://gitflic.ru/project/mikron-mik32/mik32-uploader.git#v0.2.1
board = mik32v2
framework = framework-mik32v2-sdk
board_build.ldscript = eeprom
monitor_speed = 115200
build_flags =
  -Iinclude
  -Imodel
  -DMAX_TEST_VECTOR_BYTES=1024
  -DMAX_BATCH=64
  -DPROTO_TIMEOUT_MS=2000

upload_protocol = custom
upload_command = python ../tools/runner/mik32_upload.py "$SOURCE"
